In [1]:
from IPython.display import HTML
import requests
import pandas as pd
import numpy as np
from openpyxl import load_workbook

In [2]:
HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
<form action="javascript:code_toggle()"><input type="submit" value="Click here to toggle on/off the raw code."></form>''')

In [3]:
url_data = 'https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/2022-23/cleaned_players.csv'
url_excel = '/Users/joethorpe/Documents/Fantasy Football/FF_2023.xlsx'

In [4]:
data = pd.DataFrame(pd.read_csv(url_data))
data

,first_name,second_name,goals_scored,assists,total_points,minutes,goals_conceded,creativity,influence,threat,bonus,bps,ict_index,clean_sheets,red_cards,yellow_cards,selected_by_percent,now_cost,element_type
0,Cédric,Alves Soares,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.2,43,DEF
1,Granit,Xhaka,1,2,20,267,2,74.5,97.2,36.0,2,72,20.8,2,0,1,2.5,50,MID
2,Mohamed,Elneny,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,1.3,44,MID
3,Rob,Holding,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.1,43,DEF
4,Thomas,Partey,0,0,8,270,2,21.5,41.2,49.0,0,39,11.2,2,0,0,0.6,50,MID
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,Joseph,Hodge,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,45,MID
588,Connor,Ronan,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.1,45,MID
589,Chem,Campbell,0,0,1,5,0,0.0,0.0,0.0,0,2,0.0,0,0,0,0.3,45,MID
590,Gonçalo Manuel,Ganchinho Guedes,0,0,3,112,1,38.1,5.4,41.0,0,8,8.4,0,0,0,0.2,60,MID
591,Matheus Luiz,Nunes,0,0,2,90,1,14.9,6.2,34.0,0,12,5.5,0,0,0,0.1,50,MID

In [5]:
#data.to_excel(url_excel, sheet_name='Data Input')

book = load_workbook(url_excel)

writer = pd.ExcelWriter(url_excel, engine='openpyxl') 

writer.book = book

writer.sheets = dict((ws.title, ws) for ws in book.worksheets)

data.to_excel(writer, sheet_name="Data_Input")

writer.save()

In [6]:
print('Update Complete')

Update Complete